- coap-service-nanomesh/coap_server_impl.c
- module.json
- source/coap_server.c
- source/coap_service.c
- source/include/coap_server.h
- source/include/coap_server_impl.h
-Updated dependencies
-Removed compiler warnings
> Update dependencies and remove compiler warnings

- module.json
- source/coap_security_handler.c
> random fix

- source/coap_connection_handler.c
@mikter @AnttiKauppila please review
> added a missing call to socket free

- source/coap_connection_handler.c
- source/coap_service_api.c
- test/coap-service/unittest/coap_service_api/test_coap_service_api.c
@mikter @deepakvenugopal to review
> Check for return status when opening socket

- source/coap_connection_handler.c
- source/coap_security_handler.c
- test/coap-service/unittest/coap_connection_handler/Makefile
- test/coap-service/unittest/coap_connection_handler/test_coap_connection_handler.c
- test/coap-service/unittest/coap_security_handler/test_coap_security_handler.c
- test/coap-service/unittest/stub/mbedtls_stub.c
- test/coap-service/unittest/stub/mbedtls_stub.h
- test/coap-service/unittest/stub/timeout_stub.c
- mbedtls timer implementation changed to use event timer.
- Connection handler to return all error cases
@AnttiKauppila @mikter - review
> CoAP service refactoring:

- source/coap_connection_handler.c
> Close and clear session when error received after connection is

- coap-service/coap_service_api.h
- source/coap_connection_handler.c
- source/coap_security_handler.c
- source/coap_service_api.c
- source/include/coap_connection_handler.h
- source/include/coap_security_handler.h
- test/coap-service/unittest/coap_security_handler/test_coap_security_handler.c
- test/coap-service/unittest/stub/coap_connection_handler_stub.c
- test/coap-service/unittest/stub/coap_security_handler_stub.c
> API for changing DTLS handshake message timeouts.

- source/coap_security_handler.c
- source/include/coap_security_handler.h
> Defines for default timeout values

- source/coap_connection_handler.c
- source/coap_security_handler.c
- source/coap_service_api.c
- source/include/coap_connection_handler.h
- source/include/coap_service_api_internal.h
- test/coap-service/unittest/coap_connection_handler/Makefile
- test/coap-service/unittest/coap_connection_handler/test_coap_connection_handler.c
- test/coap-service/unittest/stub/coap_connection_handler_stub.c
- test/coap-service/unittest/stub/coap_service_api_stub.c
- fix for IOTTHD-575
- Timers to remove sessions
@mikter @artokin to review
> Thread iop 10

- source/include/coap_security_handler.h
> Changed DTLS_HANDSHAKE_TIMEOUT_MAX 125s -> 201s

- coap-service/coap_service_api.h
- module.json
- source/coap_message_handler.c
- source/include/coap_message_handler.h
for source address and source port.
@mikter @artokin @deepakvenugopal
> Modified coap response callback, added parameters

- source/coap_connection_handler.c
> Set link layer security when opening socket.

- source/coap_message_handler.c
- source/coap_service_api.c
- source/include/coap_service_api_internal.h
If coap service library receives confirmable request to URI that is not
registered, it must send response COAP_MSG_CODE_RESPONSE_NOT_FOUND.
> Send 4.04 if URI is not found

- source/coap_connection_handler.c
Secure sending code was passing the remote address as the source
address, bizarrely. This records the local address last used as the
destination for incoming packets and uses that.
Other fix-ups:
* dest_addr (ie remote address) removed from internal_socket_t; this isn't
safe, as one socket talks to multiple remote peers. Use address in
secure_session_t instead.
* Some renaming: listen_socket->socket, send/receive callbacks,
remote_address+remote_port -> remote_host
> Fix secure operation; some name and logical tidies

- source/coap_message_handler.c
In some callbacks, secure session might be removed and transactions been
freed. That leads to double freeing, and reading from freed pointer.
Transaction is now removed from list before calling callback to avoid
that.
> Remove transaction from list before callback call

- source/coap_connection_handler.c
This field member was wrongly named - it should have been msg_flags.
I'm planning to correct it, which is a compatibility break.
As this doesn't need to actually set any flags for sendmsg(), use
designated initialiser to get it automatically zero-filled, so this code
will work with both old and new naming.
For recvmsg() the flags are output-only, so no need to set it when
making the call.
> Avoid referencing ns_msghdr_t::flags

- test/coap-service/unittest/stub/eventOS_event_stub.c
Remove unnecessary stub eventOS_event_send
> Update unit tests

- Makefile
- coap-service/coap_service_api.h
- source/coap_message_handler.c
- source/coap_service_api.c
- source/include/coap_message_handler.h
- test/coap-service/unittest/makefile_defines.txt
- test/coap-service/unittest/stub/coap_service_api_stub.c
- test/coap-service/unittest/stub/sn_coap_parser_stub.c
- test/coap-service/unittest/stub/sn_coap_protocol_stub.c
This PR is linked with https://github.com/ARMmbed/mbed-client-c/pull/121 and https://github.com/ARMmbed/mbed-client-c/pull/119
> Modifying Makefile and source file based on new coap library

- coap-service/coap_service_api.h
- source/coap_connection_handler.c
- source/coap_message_handler.c
- source/coap_service_api.c
- source/include/coap_message_handler.h
- test/coap-service/unittest/coap_message_handler/coap_message_handlertest.cpp
- test/coap-service/unittest/coap_message_handler/test_coap_message_handler.c
- test/coap-service/unittest/coap_message_handler/test_coap_message_handler.h
- test/coap-service/unittest/coap_service_api/coap_service_apitest.cpp
- test/coap-service/unittest/coap_service_api/test_coap_service_api.c
- test/coap-service/unittest/coap_service_api/test_coap_service_api.h
- test/coap-service/unittest/stub/coap_message_handler_stub.c
Allow deletion of ongoing transaction.
> Add transaction delete to CoAP service

- test/coap-service/unittest/stub/nsdynmemLIB_stub.c
- test/coap-service/unittest/stub/nsdynmemLIB_stub.h
Update unittests to cope with new nsdynmemlib API.
> Update unittests for nsdynmemlib API change

- coap-service/coap_service_api.h
- source/coap_connection_handler.c
- source/coap_security_handler.c
- source/coap_service_api.c
- source/include/coap_connection_handler.h
- source/include/coap_security_handler.h
- test/coap-service/unittest/coap_connection_handler/test_coap_connection_handler.c
- test/coap-service/unittest/coap_security_handler/test_coap_security_handler.c
- test/coap-service/unittest/coap_service_api/Makefile
- test/coap-service/unittest/coap_service_api/coap_service_apitest.cpp
- test/coap-service/unittest/coap_service_api/test_coap_service_api.c
- test/coap-service/unittest/coap_service_api/test_coap_service_api.h
- test/coap-service/unittest/stub/coap_connection_handler_stub.c
- test/coap-service/unittest/stub/coap_connection_handler_stub.h
Added API for setting certificates for client mode.
@mikter  @artokin - please review
> Support for certificate mode

- coap-service/coap_service_api.h
- source/coap_security_handler.c
- source/coap_service_api.c
- source/include/coap_security_handler.h
- test/coap-service/unittest/coap_service_api/test_coap_service_api.c
One pointer only for certificate chain data.¨
@mikter
> Certificate set API changed.

- source/coap_security_handler.c
Set certificate configuration also when working in server mode.
@mikter - please check
> Added server mode certificate conf

- coap-service/coap_service_api.h
- source/coap_message_handler.c
- source/coap_service_api.c
- source/include/coap_message_handler.h
- test/coap-service/unittest/stub/coap_message_handler_stub.c
API to send response to request, using request's message ID as a identifier.
> Add API to send response to request based on Message ID

- coap-service/coap_service_api.h
- source/coap_message_handler.c
- source/coap_service_api.c
- source/include/coap_message_handler.h
- test/coap-service/unittest/coap_message_handler/coap_message_handlertest.cpp
- test/coap-service/unittest/coap_message_handler/test_coap_message_handler.c
- test/coap-service/unittest/coap_message_handler/test_coap_message_handler.h
- test/coap-service/unittest/coap_service_api/coap_service_apitest.cpp
- test/coap-service/unittest/coap_service_api/test_coap_service_api.c
- test/coap-service/unittest/coap_service_api/test_coap_service_api.h
- test/coap-service/unittest/stub/coap_message_handler_stub.c
Add new API to delete requests from specific service ID.
> New API to clear requests by service ID

- source/coap_message_handler.c
- test/coap-service/unittest/stub/coap_message_handler_stub.c
Use provided callback function when deleting request.
> Use callback function when deleting request

- test/coap-service/unittest/coap_connection_handler/coap_connection_handlertest.cpp
- test/coap-service/unittest/coap_connection_handler/main.cpp
- test/coap-service/unittest/coap_message_handler/coap_message_handlertest.cpp
- test/coap-service/unittest/coap_message_handler/main.cpp
- test/coap-service/unittest/coap_security_handler/coap_security_handlertest.cpp
- test/coap-service/unittest/coap_security_handler/main.cpp
- test/coap-service/unittest/coap_service_api/coap_service_apitest.cpp
- test/coap-service/unittest/coap_service_api/main.cpp
Adjust also cpp-files, they were missing from the previous commit.
> Use Mbed OS coding style

- test/coap-service/unittest/stub/mbedtls_stub.c
Sync content of `mbed-os/features/nanostack/coap-service/` with this repository.
> Sync with Mbed OS coap service

- source/coap_security_handler.c
- test/coap-service/unittest/stub/mbedtls_stub.c
- test/coap-service/unittest/stub/mbedtls_stub.h
Fetch latest changes from Mbed OS.
> Sync with mbedos

- test/coap-service/unittest/coap_connection_handler/test_coap_connection_handler.c
Sync coap-service  with changes made to mbed-os/features/nanostack/coap-service
> Sync with Mbed OS

- source/coap_message_handler.c
Fix 324966 Dereference before null check
> Fix error found by coverity

- coap-service/coap_service_api.h
> Sync from Mbed OS

- Makefile
- Makefile.test
- run_unit_tests.sh
- test/coap-service/unittest/Makefile
- test/coap-service/unittest/MakefileWorker.mk
- test/coap-service/unittest/coap_connection_handler/Makefile
- test/coap-service/unittest/coap_message_handler/Makefile
- test/coap-service/unittest/coap_security_handler/Makefile
- test/coap-service/unittest/coap_service_api/Makefile
- test/coap-service/unittest/makefile_defines.txt
- test/coap-service/unittest/run_tests
- xsl_script.sh
-Change Arm Limited to Pelion.
> Update copyright to Makefiles and scripts
