- source/coap_security_handler.c
- test/coap-service/unittest/stub/mbedtls_stub.c
Added initialisations for mbed TLS startup
Fix keyblock export
@AnttiKauppila @terhei @deepakvenugopal  please check
> Coap service security fixes

- source/coap_security_handler.c
@AnttiKauppila 
This do-while loop blocks the Thread testing, as there is no mechanism for it to stop. This happens when we try to stop the device.
> Limit the number of mbed_ssl_read() in while loop.

- source/coap_security_handler.c
- source/include/coap_security_handler.h
This change allows the mbed TLS type mbedtls_timer_t to be defined, required
for the upstream version of mbed TLS (> version 2.2.1).
Without this change, coap-service shouldn't build with the development head of mbed TLS.
> Fixes coap-service for development head of mbed TLS

- coap-service/coap_service_api.h
- source/coap_connection_handler.c
- source/coap_message_handler.c
- source/coap_security_handler.c
- source/coap_service_api.c
- source/include/coap_message_handler.h
- test/coap-service/unittest/stub/coap_message_handler_stub.c
- test/coap-service/unittest/stub/coap_service_api_stub.c
-Update content_type to be sn_coap_content_format_e instead of uint8_t to avoid type conversion (bugs).
-Fix compiler warnings
> Update content_type to sn_coap_content_format_e

- module.json
- source/coap_message_handler.c
- test/coap-service/unittest/coap_message_handler/test_coap_message_handler.c
- test/coap-service/unittest/stub/coap_message_handler_stub.h
- test/coap-service/unittest/stub/sn_coap_parser_stub.c
Mbed-client-c has been refactored to be more memory efficient.
Coap-service is updated to reflect to those changes
> Coap option tidy

- source/coap_security_handler.c
Flag function mbedtls_ssl_conf_dtls_cookies with MBEDTLS_SSL_SRV_C
to enable SSL server disabling that can save flash ~3,2kB.
> Add mbedtls flag to SSL server spesific function

- source/coap_service_api.c
- test/coap-service/unittest/coap_message_handler/Makefile
- test/coap-service/unittest/coap_service_api/Makefile
- test/coap-service/unittest/stub/coap_service_api_stub.c
- test/coap-service/unittest/stub/common_functions_stub.c
Adding missing stubs, and added check for nullpointer to coap message
process callback.
@artokin
> Fix unittests

- source/coap_connection_handler.c
This fixes unstability issues. Still need to refactor
coap_security_handler_read()-function to work as specified in mbedTLS
documentation. This commit should be treated as a temporary fix.
@artokin
> Fix session lost issue

- source/coap_message_handler.c
- source/coap_service_api.c
- source/include/coap_message_handler.h
- test/coap-service/unittest/stub/coap_message_handler_stub.c
When sending non-confirmable request that is not supposed to get reply,
it must be deleted after sending.
Also some general code-cleaning included.
@mikter @artokin - plese review
> Delete transactions that are not supposed to get reply

- source/coap_connection_handler.c
- source/coap_message_handler.c
- source/coap_security_handler.c
- source/coap_service_api.c
- source/include/coap_connection_handler.h
- source/include/coap_message_handler.h
- source/include/coap_security_handler.h
- test/coap-service/unittest/coap_connection_handler/test_coap_connection_handler.c
- test/coap-service/unittest/coap_message_handler/Makefile
- test/coap-service/unittest/coap_message_handler/test_coap_message_handler.c
- test/coap-service/unittest/coap_security_handler/Makefile
- test/coap-service/unittest/coap_service_api/test_coap_service_api.c
- test/coap-service/unittest/stub/coap_connection_handler_stub.c
- test/coap-service/unittest/stub/coap_connection_handler_stub.h
- test/coap-service/unittest/stub/coap_message_handler_stub.c
- test/coap-service/unittest/stub/coap_security_handler_stub.c
- test/coap-service/unittest/stub/coap_security_handler_stub.h
- test/coap-service/unittest/stub/randLIB_stub.c
- test/coap-service/unittest/stub/socket_api_stub.c
When receiving data, destination (own) address is stored and given to
socket when sending reply to make sure respone comes always from same
address where request was sent. This commit supports only real socket to
real socket messages, not virtual socket, or DTLS handshake messages.
@mikter @deepakvenugopal @artokin - please review
> Support for setting source address to socket

- source/coap_connection_handler.c
- source/coap_security_handler.c
- source/include/coap_security_handler.h
- test/coap-service/unittest/coap_connection_handler/test_coap_connection_handler.c
- test/coap-service/unittest/coap_security_handler/test_coap_security_handler.c
- test/coap-service/unittest/makefile_defines.txt
- test/coap-service/unittest/stub/coap_security_handler_stub.c
- test/coap-service/unittest/stub/coap_security_handler_stub.h
NS_USE_EXTERNAL_MBED_TLS now controls whether we attempt to include
mbedTLS header files at all, and after including them, we check whether
SSL/TLS is enabled. If not, we provide non-secure operation only.
> Allow build without SSL

- source/coap_connection_handler.c
- source/coap_message_handler.c
- source/include/coap_message_handler.h
- source/include/coap_service_api_internal.h
- test/coap-service/unittest/coap_connection_handler/Makefile
- test/coap-service/unittest/stub/coap_message_handler_stub.c
- test/coap-service/unittest/stub/coap_service_api_stub.c
- test/coap-service/unittest/stub/sn_coap_protocol_stub.c
When handshake fails, or DTLS session is closed, all transactions must
be removed from coap protocol retransmission queue. Otherwise coap
retransmission will start new handshake.
> Delete all transactions when secure session is closed

- Makefile
-Do not define mbedtls configuration in Makefile as the same makefile
is used in target builds.
> Remove mbedtls configuration from Makefile

- test/coap-service/unittest/stub/socket_api_stub.c
* As part of patch-2 for socket API update, we need to add 2nd parameter of socket_listen() API.
> Addding backlog parameter to socket_listen

- source/coap_connection_handler.c
- source/coap_message_handler.c
- test/coap-service/unittest/stub/socket_api_stub.c
If response to multicast request is sent, local address must be set to
default.
@artokin @mikter @jpellikk-arm - please review
> Use default local address, if request is from multicast address

- source/coap_connection_handler.c
- test/coap-service/unittest/stub/socket_api_stub.c
* Pertaining to new socket API changes, socket_free is deprecated.
* socket_close() is used from now on.
* Fixing stubs too.
> Using socket_close() instead of socket_free()

- source/coap_connection_handler.c
- source/coap_message_handler.c
When secure session is deleted, transaction callback must be called
to inform request sender that response is not going to be received.
> Call transaction callback when transactions are deleted

- source/coap_security_handler.c
- test/coap-service/unittest/coap_security_handler/test_coap_security_handler.c
Middleware components are not allowed to add strong entropy sources
to mbedtls.
Preprocessor directive is used as some old applications might rely on
having entropy source in coap-service.
> Flag out entropy source addition

- source/coap_connection_handler.c
After socket API changes, send function returns actual number of bytes
sent. That caused int8_t to overflow, and to be read as a negative
number, meaning error. Changed return values to be 'int' instead.
Also, added check for socket event type. Now we skip all but SOCKET_DATA
events.
@artokin @kjbracey-arm @hasnainvirk - please review
> Fix socket send return value overflow

- source/coap_connection_handler.c
- source/coap_service_api.c
Socket id is initialized to -1 when virtual service is used.
Therefore it is not possible to search virtual service based on
socket id.
Use negative socket id's to identify virtual services.
share same socket ID coap-service supports one virtual socket.
> Support for multiple virtual services

- source/coap_connection_handler.c
When timer callback is called, void pointer is given as a parameter, and
it is then typecasted to secure session pointer. Added check is that
session still valid before using it.
@deepakvenugopal - please verify
> Check secure session pointer in timer callback

- coap-service/coap_service_api.h
- source/coap_connection_handler.c
- source/coap_service_api.c
- source/include/coap_connection_handler.h
- test/coap-service/unittest/coap_connection_handler/test_coap_connection_handler.c
- test/coap-service/unittest/stub/coap_connection_handler_stub.c
Add new COAP service option COAP_SERVICE_OPTIONS_SELECT_SOCKET_IF.
When option is set then COAP interface ID will be selected as socket
interface.
> Add option to select used socket interface

- coap-service/coap_service_api.h
- source/coap_connection_handler.c
- source/coap_service_api.c
COAP service registers automatically to COAP multicast groups:
-ff02::fd (link-local according to RFC 7390)
-ff05::fd (site local according to RFC 7390)
> Register to multicast groups

- coap-service/coap_service_api.h
- source/coap_connection_handler.c
- source/coap_service_api.c
- source/include/coap_connection_handler.h
- test/coap-service/unittest/coap_connection_handler/test_coap_connection_handler.c
- test/coap-service/unittest/stub/coap_connection_handler_stub.c
Option COAP_SERVICE_OPTIONS_MULTICAST_JOIN added to service_api to
join COAP multicast group. The group is left when service is deleted.
> Add option to join COAP multicast group

- coap-service/coap_service_api.h
- source/coap_message_handler.c
- source/coap_service_api.c
- source/include/coap_message_handler.h
- test/coap-service/unittest/coap_service_api/Makefile
To save some memory, CoAP duplicate message detection is disabled by
default.
> Disable CoAP duplicate message detection

- source/include/coap_security_handler.h
-Use guards around MBEDTLS macros.
> Fix redefinition of mbed TLS error codes

- source/coap_message_handler.c
- source/coap_service_api.c
Changes to message transaction handling:
- when receiving request, parsed request message is freed after callback call,
not when sending response
- transaction is deleted when sending response
> Message transaction memory handling changes

- coap-service/coap_service_api.h
- source/coap_message_handler.c
- source/coap_service_api.c
When response is not expected, transaction can be deleted after sending.
Transaction deleted depending on resource callback return value
> Delete transaction when not needed

- source/coap_connection_handler.c
- source/coap_message_handler.c
- source/coap_service_api.c
- source/include/coap_connection_handler.h
- test/coap-service/unittest/coap_connection_handler/test_coap_connection_handler.c
- test/coap-service/unittest/coap_message_handler/test_coap_message_handler.c
Before, in some error cases coap_connection_handler_send_data() returned value
-2 that caused data pointer to be saved. That might leak memory, if data pointer
was already allocated.
> Fix coap_connection_handler_send_data() return values

- source/include/coap_security_handler.h
Include mbedtls config files before including ssl.h to avoid
error: "mbedtls\ssl.h",384 Error[Pe169]: expected a declaration"
> Fix IAR compilation error with NUCLEO_F401RE

- Makefile
- source/coap_message_handler.c
- source/include/coap_message_handler.h
Token length was limited to 4 bytes. Fixed coap service to handle token length
up to 8 bytes.
Enabled debug traces in all builds.
> Fix transactions to handle all token lengths

- source/coap_message_handler.c
Reverting address check from transaction find function. This needs more work,
and full functionality will be added in the future commits.
> Reverting address check from transaction find

- source/coap_message_handler.c
Fixed invalid memory read error. Transaction can be freed in tx-callback, it
should not be used after that.
> Fix invalid memory read error

- source/coap_connection_handler.c
- source/coap_message_handler.c
- source/coap_service_api.c
- source/include/coap_connection_handler.h
- source/include/coap_message_handler.h
- test/coap-service/unittest/coap_message_handler/test_coap_message_handler.c
- test/coap-service/unittest/coap_service_api/coap_service_apitest.cpp
- test/coap-service/unittest/coap_service_api/test_coap_service_api.c
- test/coap-service/unittest/coap_service_api/test_coap_service_api.h
- test/coap-service/unittest/stub/coap_connection_handler_stub.c
- test/coap-service/unittest/stub/coap_connection_handler_stub.h
- test/coap-service/unittest/stub/coap_message_handler_stub.c
- test/coap-service/unittest/stub/coap_message_handler_stub.h
Check that receive interface ID is matching to interface ID registered to URI.
> Add check for interface when receiving CoAP request

- source/coap_message_handler.c
- source/include/coap_message_handler.h
- test/coap-service/unittest/coap_message_handler/Makefile
- test/coap-service/unittest/coap_message_handler/test_coap_message_handler.c
Some improvements/fixes for the CoAP transaction delete:
- Calculate transaction lifetime from CoAP retransmission maximum times
- When transaction times out, callback must be called to inform that transaction
was failed
> CoAP transaction delete improvements

- source/coap_message_handler.c
- test/coap-service/unittest/coap_message_handler/test_coap_message_handler.c
Some applications need to wait for COAP response before they can
continue. The COAP response timeout could be shortened when remote
device is not sending the response.
Adjust request message lifetime based on sn_coap_protocol message
builder return value.
> Adjust request message validity lifetime

- source/coap_connection_handler.c
- source/coap_message_handler.c
- source/coap_service_api.c
- source/include/coap_connection_handler.h
- source/include/coap_message_handler.h
- test/coap-service/unittest/coap_message_handler/test_coap_message_handler.c
- test/coap-service/unittest/coap_service_api/coap_service_apitest.cpp
- test/coap-service/unittest/coap_service_api/test_coap_service_api.c
- test/coap-service/unittest/coap_service_api/test_coap_service_api.h
- test/coap-service/unittest/stub/coap_connection_handler_stub.c
- test/coap-service/unittest/stub/coap_connection_handler_stub.h
- test/coap-service/unittest/stub/coap_message_handler_stub.c
- test/coap-service/unittest/stub/coap_message_handler_stub.h
This reverts commit a4bb497d8f0e9731fe8c8a5f5be859ebf6886074.
This commit breaks commissioner functionality.
> Revert "Add check for interface when receiving CoAP request (#92)"

- source/coap_security_handler.c
Fixed following two compiler warnings:
'simple_cookie_check' defined but not used
'simple_cookie_write' defined but not used
> Fixed compiler warnings

- source/coap_connection_handler.c
Check return value from function coap_security_handler_connect_non_blocking and
remove secure session if connection fails.
> Check for coap_security_handler_connect_non_blocking return value

- coap-service/coap_service_api.h
- source/coap_message_handler.c
- source/coap_service_api.c
- source/include/coap_message_handler.h
- test/coap-service/unittest/coap_message_handler/test_coap_message_handler.c
- test/coap-service/unittest/stub/sn_coap_builder_stub.c
- test/coap-service/unittest/stub/sn_coap_protocol_stub.c
- sn_coap_protocol_parse() might call tx-callback. Create transaction before
calling that.
- Call prepare_blockwise_message() before sending CoAP message. This adds
dependency to internal coap header file, and anyhow needs to be done inside the
coap protocol library.
> CoAP blockwise transfer support

- source/coap_service_api.c
Fixed warning caused by from unused parameter 'service_id' in
coap_service_blockwise_size_set - function.
> Fix 'unused variable' compiler - warning

- source/coap_connection_handler.c
- source/coap_service_api.c
Fixed session cleanup timer bugs:
- secure session exec interval operator logic fixed
- changed ns_list_foreach to ns_list_foreach_safe in session delete loop
> Session cleanup timer fixes

- coap-service/coap_service_api.h
- source/coap_connection_handler.c
- source/coap_message_handler.c
- source/coap_service_api.c
- source/include/coap_connection_handler.h
- source/include/coap_message_handler.h
- test/coap-service/unittest/coap_connection_handler/coap_connection_handlertest.cpp
- test/coap-service/unittest/coap_connection_handler/test_coap_connection_handler.c
- test/coap-service/unittest/coap_connection_handler/test_coap_connection_handler.h
- test/coap-service/unittest/coap_service_api/Makefile
- test/coap-service/unittest/coap_service_api/coap_service_apitest.cpp
- test/coap-service/unittest/coap_service_api/test_coap_service_api.c
- test/coap-service/unittest/coap_service_api/test_coap_service_api.h
- test/coap-service/unittest/stub/coap_connection_handler_stub.c
- test/coap-service/unittest/stub/coap_connection_handler_stub.h
- test/coap-service/unittest/stub/coap_message_handler_stub.c
Application can set message prevalidation callback method that can be used to validate incoming message before passing it further.
> Add API to set callback for CoAP msg prevalidation

- coap-service/coap_service_api.h
- source/coap_connection_handler.c
- source/coap_message_handler.c
- source/coap_service_api.c
- source/include/coap_connection_handler.h
- source/include/coap_message_handler.h
- test/coap-service/unittest/coap_connection_handler/coap_connection_handlertest.cpp
- test/coap-service/unittest/coap_connection_handler/test_coap_connection_handler.c
- test/coap-service/unittest/coap_connection_handler/test_coap_connection_handler.h
- test/coap-service/unittest/coap_message_handler/test_coap_message_handler.c
- test/coap-service/unittest/coap_service_api/test_coap_service_api.c
- test/coap-service/unittest/stub/coap_connection_handler_stub.c
- test/coap-service/unittest/stub/coap_connection_handler_stub.h
- test/coap-service/unittest/stub/coap_message_handler_stub.c
- test/coap-service/unittest/stub/coap_message_handler_stub.h
- test/coap-service/unittest/stub/mbedtls_stub.c
-Change prevalidation API to use socket listen port instead of service ID
-Add new internal method to find connection handler based on socket port
-Add receiving interface ID to callback API
-Reorder callback parameters
-Update function coap_message_handler_coap_msg_process signature
**Note**! This PR requires corresponding API changes to Nanostack
> Update message prevalidation API

- source/coap_connection_handler.c
Move ancillary_databuffer away from sub-block so that compiler does
not optimize the code away.
> Adjust variable scope

- test/coap-service/unittest/MakefileWorker.mk
- test/coap-service/unittest/coap_message_handler/test_coap_message_handler.c
- test/coap-service/unittest/stub/sn_coap_builder_stub.c
-Change updated COAP APIs to sn_coap_builder_stub
-Fix message_handler test
> Match COAP test stub to updated mbed-coap API

- source/coap_security_handler.c
- source/include/coap_security_handler.h
- test/coap-service/unittest/coap_security_handler/test_coap_security_handler.c
- test/coap-service/unittest/stub/mbedtls_stub.c
Disabled key material export for now, needs to be updated later to new key export function if needed. Made the SSL state to refer to private state for now. Do not include config, instead include version.h that is present in both 2.0 and 3.0 and will include config and defines version macros.
> Updated coap service to be compatible with mbed TLS 3.0
